dist: xenial
sudo: true

language: python

services:
  - postgresql

matrix:
  include:
  - python: 2.7
    env: DJANGO=1.11
  - python: 3.6
    env: DJANGO=2.2
  - python: 3.7
    env: DJANGO=3.0
  - python: 3.8
    env: DJANGO=3.0

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

before_script:
  - export DJANGO_SETTINGS_MODULE=settings
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - psql -c "create extension postgis;" -U postgres

install:
  - pip install -r requirements.txt
  - pip install pytest coveralls
  - pip install Django~=${DJANGO}.0

script:
  - pytest

after_success:
  - coveralls
