dist: xenial
sudo: true

language: python

matrix:
  include:
  - python: 2.7
    env: DJANGO=1.11
  - python: 3.6
    env: DJANGO=2.2
  - python: 3.7
    env: DJANGO=3.0
  - python: 3.8
    env: DJANGO=3.0

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install Django~=${DJANGO}.0

script:
  - pytest

after_success:
  - coveralls
