dist: xenial
sudo: true

language: python

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - libgdal-dev
    - postgresql-10
    - postgresql-10-postgis-2.4
    - libgdal-dev

matrix:
  include:
  - python: 2.7
    env: DJANGO=1.11
  - python: 3.6
    env: DJANGO=2.2
  - python: 3.7
    env: DJANGO=3.0
  - python: 3.8
    env: DJANGO=3.0

before_script:
  - export DJANGO_SETTINGS_MODULE=settings
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  # check gis
  - gdal-config --version
  - gdal-config --cflags
  - psql -U postgres -c "create extension postgis"
  # set up postgresql
  - psql -U postgres -c "create role cacheops login superuser"
  # postgis django backend requires these to exist
  - psql -U postgres -c "create database cacheops"
  - psql -U postgres -c "create database cacheops_slave"

install:
  - pip install -r requirements.txt
  - pip install psycopg2 pytest coveralls
  - pip install Django~=${DJANGO}.0

script:
  - pytest --reuse-db --migrations --create-db

after_success:
  - coveralls
