dist: trusty
sudo: true

language: python
python:
  - 2.7
  - 3.6

install:
  - pip install tox
  - pip install coveralls
  #- pip install python-coveralls

env:
  - DJANGO=django18
  - DJANGO=django19
  - DJANGO=django110
  - DJANGO=django111
  # - DJANGO=django20

# Workaround for Travis issues with unknown python interpreters
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=django20

script:
  - tox -e $DJANGO-py${TRAVIS_PYTHON_VERSION//[.]/}

after_success:
  - coveralls
