dist: trusty
sudo: true

language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install tox
  - pip install coveralls
  #- pip install python-coveralls

env:
  - DJANGO=django111
  # - DJANGO=django20

# Workaround for Travis issues with unknown python interpreters
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=django20

script:
  - mkdir -p env/bin
  - ln -s pytest env/bin/pytest
  - tox -e $DJANGO-py${TRAVIS_PYTHON_VERSION//[.]/}

after_success:
  - coveralls
