dist: trusty
sudo: false

language: python

install:
  - pip install tox
  - pip install coveralls
  #- pip install python-coveralls

script:
  - tox

env:
  - TOXENV=django17-py27
  - TOXENV=django17-py33
  - TOXENV=django18-py27
  - TOXENV=django18-py34
  - TOXENV=django19-py27
  - TOXENV=django19-py35
  - TOXENV=django110-py27
  - TOXENV=django110-py35
  - TOXENV=django111-py27
  - TOXENV=django111-py36
  - TOXENV=django20-py36

after_success:
  - coveralls
